import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** Whitelabel logo shown on documents IMCRM generates itself
   *  (receipts today; future reports) — never on the official NFS-e
   *  PDF, whose layout the municipality/Asaas controls (migration 064). */
  logo_url: string | null;
  legal_name: string | null;
  cnpj: string | null;
  store_slug: string | null;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  /**
   * Which WhatsApp integration is currently live for this account.
   * One provider active at a time (037_baileys_integration.sql) —
   * switching providers is a Settings action, not a merge of two
   * simultaneous connections.
   */
  active_whatsapp_provider: WhatsAppProviderType;
  created_at: string;
  updated_at: string;
}

/**
 * `meta_cloud_api` — the official Meta WhatsApp Business Cloud API
 * (`whatsapp_config` table, `src/lib/whatsapp/meta-api.ts`).
 * `baileys` — unofficial WhatsApp Web protocol via the whatsapp-worker
 * service (`baileys_connections` table). Added in
 * 037_baileys_integration.sql.
 * `instagram` — Instagram Graph API messaging (`instagram_configs`
 * table, `src/lib/instagram/graph-api.ts`). Added in migration 050.
 * Never a valid value for `accounts.active_whatsapp_provider` (that
 * column only toggles between the two WhatsApp providers) — this is
 * for `messages.provider`, which shares the same DB enum.
 */
export type WhatsAppProviderType = 'meta_cloud_api' | 'baileys' | 'instagram';

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  /**
   * Nullable since migration 050 — an Instagram-originated contact has
   * no phone number; it's identified by `instagram_scoped_id` instead.
   * Every WhatsApp send path still requires it (guarded explicitly),
   * so a WhatsApp-originated contact always has one in practice.
   */
  phone: string | null;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  /** Instagram-scoped id (IGSID) of the commenter/DM sender — set only
   *  for Instagram-originated contacts (migration 050). */
  instagram_scoped_id?: string | null;
  instagram_username?: string | null;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export type ConversationChannel = 'whatsapp' | 'instagram';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  /** Which platform this thread lives on (migration 050). Defaults to
   *  'whatsapp' — every conversation before this migration is one. */
  channel: ConversationChannel;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  /** Legacy pre-composed English text — kept for backward compat but
   *  no longer rendered; the UI builds a localized string from
   *  contact_name/actor_name via next-intl instead (migration 040). */
  title: string;
  body?: string;
  /** Display-name snapshots for i18n-safe rendering (migration 040). */
  contact_name?: string | null;
  actor_name?: string | null;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  /**
   * Which provider this message was sent/received through. Nullable —
   * only populated by call sites written after
   * 037_baileys_integration.sql; older rows (all Meta) leave it unset.
   */
  provider?: WhatsAppProviderType;
  /**
   * Provider-agnostic counterpart to `message_id` (which historically
   * only ever held a Meta `wamid`). New call sites set both; reads
   * are migrating to this column incrementally.
   */
  provider_message_key?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

export interface InstagramConfig {
  id: string;
  account_id: string;
  page_id: string;
  instagram_business_account_id: string;
  access_token: string;
  verify_token?: string;
  username?: string;
  status: 'connected' | 'error';
  last_error?: string;
  connected_at?: string;
}

export type BaileysConnectionStatus =
  'disconnected' | 'qr_pending' | 'connected';

/**
 * One row per account — tracks the lifecycle of that account's
 * WhatsApp Web (Baileys) pairing. 037_baileys_integration.sql.
 */
export interface BaileysConnection {
  id: string;
  account_id: string;
  status: BaileysConnectionStatus;
  phone_number?: string;
  /** Data-URL PNG of the current pairing QR, set while status === 'qr_pending'. */
  qr_code?: string;
  connected_at?: string;
  last_seen_at?: string;
  created_at: string;
  updated_at: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed' | 'skipped';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /** Consent-suppressed recipients; never counted as provider failures. */
  skipped_count: number;
  /** Invalid phones rejected before a recipient row could be created. */
  rejected_recipients?: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /** Dispatched by the billing nurture cron (src/app/api/billing/
   *  nurture-cron/route.ts) for a signed-up account that still hasn't
   *  subscribed 24h after creation — carries a freshly generated 20%
   *  coupon in context.vars. */
  | 'billing_nudge_24h'
  /** Same cron, 48h mark — offers a 7-day free trial instead. */
  | 'billing_nudge_48h'
  /** Dispatched by /api/orders/webhook on PAYMENT_CONFIRMED — lets a
   *  tenant build a post-purchase automation (thank-you message, tag
   *  the contact as a buyer, etc.) without touching the Flow that
   *  created the order. context.vars carries order_id/total_cents. */
  | 'order_paid'
  /** Fired by the Instagram webhook when a comment on a connected
   *  account's post matches the configured keyword(s) — the ManyChat-
   *  style "comment → DM" mechanic (migration 050). context carries
   *  `message_text` (the comment) and `vars.comment_id`/`vars.media_id`. */
  | 'instagram_comment_keyword';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  /** Sends a DM on Instagram (text or document) — see
   *  `SendInstagramDmStepConfig`. Uses the Instagram Send API's
   *  "private reply" mechanism when the run started from a comment
   *  trigger (first-touch), plain send after that. */
  | 'send_instagram_dm';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export interface InstagramCommentKeywordTriggerConfig {
  /** 'all' matches comments on any post on the connected account;
   *  'specific' scopes to `post_id` only. */
  post_filter: 'all' | 'specific';
  post_id?: string;
  keywords: string[];
  match_type?: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | InstagramCommentKeywordTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export interface SendInstagramDmStepConfig {
  message_type: 'text' | 'document';
  text?: string;
  media_url?: string;
  /** Shown as the file name for a document DM. */
  filename?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | SendInstagramDmStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Catalog / orders — a tenant's own products/services, sold through
// the `show_catalog` / `checkout` Flow node types (src/lib/flows).
// ============================================================

export interface CatalogItem {
  id: string;
  account_id: string;
  name: string;
  description: string | null;
  price_cents: number;
  currency: string;
  media_url: string | null;
  media_type: 'image' | 'video' | null;
  /** Surfaced as a suggestion at checkout to lift ticket size. */
  is_upsell: boolean;
  is_active: boolean;
  position: number;
  /** NULL = not tracked (unlimited). Decremented atomically on every
   *  checkout path (public store, comanda item add) once set. */
  stock_quantity: number | null;
  offer_type: 'physical_product' | 'service' | 'subscription';
  billing_cycle: 'MONTHLY' | 'QUARTERLY' | 'SEMIANNUALLY' | 'YEARLY' | null;
  compare_at_price_cents: number | null;
  trial_days: number;
  campaign_badge: string | null;
  sku: string | null;
  ncm: string | null;
  cest: string | null;
  cfop: string | null;
  fiscal_unit: string;
  created_at: string;
  updated_at: string;
}

export type OrderStatus = 'pending_payment' | 'paid' | 'canceled';

export type OrderSource = 'whatsapp_checkout' | 'manual' | 'public_store';

export interface Order {
  id: string;
  account_id: string;
  cart_id: string | null;
  contact_id: string | null;
  deal_id: string | null;
  /** Per-account sequential number ("Comanda #7") — assigned atomically
   *  by a DB trigger on insert (migration 066), never client-supplied. */
  order_number: number;
  order_code: string;
  status: OrderStatus;
  subtotal_cents: number;
  total_cents: number;
  currency: string;
  gateway_customer_id: string | null;
  gateway_payment_id: string | null;
  invoice_id: string | null;
  invoice_status: string | null;
  /** 'manual' = opened directly as a comanda; 'whatsapp_checkout' = created
   *  by the checkout Flow node (migration 064); 'public_store' = the
   *  customer checked out themselves on /loja/[account_id] (migration 065). */
  source: OrderSource;
  notes: string | null;
  created_at: string;
  updated_at: string;
  paid_at: string | null;
}

export interface OrderItem {
  id: string;
  order_id: string;
  catalog_item_id: string | null;
  name_snapshot: string;
  quantity: number;
  unit_price_cents: number;
  total_cents: number;
  created_at: string;
}

/** 'card' stays valid for rows recorded before the debit/credit split
 *  (migration 066) but is no longer offered as a new choice in the UI. */
export type OrderPaymentMethod =
  | 'cash'
  | 'card'
  | 'card_debit'
  | 'card_credit'
  | 'pix_manual'
  | 'pix_asaas'
  | 'other';

/** A payment recorded by hand against an order (migration 064) — cash,
 *  card, a PIX paid outside Asaas, or a split across methods. Separate
 *  from the automatic Asaas flow, which marks `orders.status` directly. */
export interface OrderPayment {
  id: string;
  account_id: string;
  order_id: string;
  method: OrderPaymentMethod;
  amount_cents: number;
  notes: string | null;
  recorded_by: string | null;
  created_at: string;
}
