'use client';
import { useCallback, useEffect, useState } from 'react';
import { Copy, Loader2, Plus, Truck } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function DriversPage() {
  const [data,setData]=useState<{drivers:any[];orders:any[]}>({drivers:[],orders:[]}); const [loading,setLoading]=useState(true); const [form,setForm]=useState({name:'',email:'',phone:'',vehicle_type:'motorcycle',vehicle_plate:''}); const [invite,setInvite]=useState('');
  const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/drivers');const d=await r.json();if(r.ok)setData(d);setLoading(false)},[]); useEffect(()=>{void load()},[load]);
  async function create(){const r=await fetch('/api/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return toast.error(d.error);setInvite(d.invite_url);toast.success('Entregador cadastrado.');void load()}
  async function assign(order_id:string,driver_id:string){if(!driver_id)return;const r=await fetch('/api/drivers/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id,driver_id})});const d=await r.json();if(!r.ok)return toast.error(d.error);toast.success(`Entrega atribuída. Código do cliente: ${d.confirmation_code}`);await navigator.clipboard.writeText(d.confirmation_code);void load()}
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Entregadores</h1><p className="text-sm text-muted-foreground">Cadastre a equipe de entrega, atribua pedidos e acompanhe as rotas periódicas.</p></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Novo entregador</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Nome completo" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input placeholder="E-mail de acesso" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input placeholder="Telefone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className="h-9 rounded-lg border bg-background px-3 text-sm" value={form.vehicle_type} onChange={e=>setForm({...form,vehicle_type:e.target.value})}><option value="motorcycle">Moto</option><option value="car">Carro</option><option value="bicycle">Bicicleta</option><option value="other">Outro</option></select><Input placeholder="Placa" value={form.vehicle_plate} onChange={e=>setForm({...form,vehicle_plate:e.target.value})}/></div><Button onClick={create}><Plus/>Cadastrar e gerar convite</Button>{invite&&<div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Envie este link ao entregador:</p><p className="mt-1 break-all text-sm">{invite}</p><Button className="mt-2" size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(invite)}><Copy/>Copiar link</Button></div>}</CardContent></Card><Card><CardHeader><CardTitle>Equipe cadastrada</CardTitle></CardHeader><CardContent>{loading?<Loader2 className="animate-spin"/>:<div className="space-y-2">{data.drivers.map(d=><div key={d.id} className="flex items-center gap-3 rounded-lg border p-3"><Truck className="text-primary"/><div><b className="block text-sm">{d.name}</b><span className="text-xs text-muted-foreground">{d.phone} · {d.status==='active'?'Ativo':'Convite pendente'}</span></div></div>)}</div>}</CardContent></Card></div><Card><CardHeader><CardTitle>Pedidos prontos para atribuição</CardTitle></CardHeader><CardContent className="space-y-2">{data.orders.length===0?<p className="text-sm text-muted-foreground">Nenhum pedido pronto aguardando entregador.</p>:data.orders.map(o=><div key={o.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><b>Pedido #{o.order_code}</b><select className="h-9 rounded-lg border bg-background px-3 text-sm" value={o.assigned_driver_id||''} onChange={e=>void assign(o.id,e.target.value)}><option value="">Selecionar entregador</option>{data.drivers.filter(d=>d.status==='active').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>)}</CardContent></Card></div>
}
